-- Migration: Ensure user_payment_methods table exists and has Pagar.me columns
CREATE TABLE IF NOT EXISTS public.user_payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    stripe_payment_method_id TEXT,
    asaas_card_token TEXT,
    pagarme_card_id TEXT,
    brand TEXT,
    last4 TEXT,
    exp_month INT,
    exp_year INT,
    is_default BOOLEAN DEFAULT FALSE,
    biometrically_validated BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Adicionar colunas individualmente se a tabela já existia
ALTER TABLE public.user_payment_methods ADD COLUMN IF NOT EXISTS pagarme_card_id TEXT;
ALTER TABLE public.user_payment_methods ADD COLUMN IF NOT EXISTS asaas_card_token TEXT;
ALTER TABLE public.user_payment_methods ADD COLUMN IF NOT EXISTS biometrically_validated BOOLEAN DEFAULT FALSE;

-- RLS
ALTER TABLE public.user_payment_methods ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage their own payment methods" ON public.user_payment_methods;
CREATE POLICY "Users can manage their own payment methods"
    ON public.user_payment_methods FOR ALL
    USING (user_id IN (SELECT id FROM public.users WHERE supabase_uid = auth.uid()));

DROP POLICY IF EXISTS "Service role can manage all payment methods" ON public.user_payment_methods;
CREATE POLICY "Service role can manage all payment methods"
    ON public.user_payment_methods FOR ALL
    USING (auth.role() = 'service_role');
