
-- Migration: MySQL to PostgreSQL (Supabase)

-- Users Table
CREATE TABLE public.users (
  id bigint generated by default as identity primary key,
  firebase_uid varchar(128) unique,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  full_name varchar(100) not null,
  role varchar(20) not null default 'client' check (role in ('client', 'provider', 'admin')),
  phone varchar(20),
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  is_verified boolean default false,
  avatar_blob bytea,
  avatar_mime varchar(64)
);

-- Providers Table (Extension of Users)
CREATE TABLE public.providers (
  user_id bigint primary key references public.users(id) on delete cascade,
  bio text,
  address varchar(255),
  rating_avg decimal(3,2) default 0.00,
  rating_count int default 0,
  wallet_balance decimal(10,2) default 0.00,
  latitude decimal(10,8),
  longitude decimal(11,8),
  is_online boolean default false,
  document_type varchar(10) check (document_type in ('cpf', 'cnpj')),
  document_value varchar(20),
  commercial_name varchar(100)
);

-- Categories
CREATE TABLE public.categories (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  icon varchar(50) default 'box',
  slug varchar(255)
);

-- Professions
CREATE TABLE public.professions (
  id bigint generated by default as identity primary key,
  name varchar(128) not null unique,
  category_id int, -- references categories(id) but can be null/loose
  icon varchar(64),
  keywords text,
  search_vector jsonb,
  popularity_score int default 0,
  service_type varchar(20) not null default 'on_site' check (service_type in ('on_site', 'at_provider', 'remote'))
);

-- Provider Professions
CREATE TABLE public.provider_professions (
  provider_user_id bigint not null references public.users(id) on delete cascade,
  profession_id int not null references public.professions(id) on delete cascade,
  fixed_price decimal(10,2),
  hourly_rate decimal(10,2),
  primary key (provider_user_id, profession_id)
);

-- Provider Locations (for geospatial optimization)
CREATE TABLE public.provider_locations (
  provider_id bigint primary key references public.users(id) on delete cascade,
  latitude decimal(10,8) not null,
  longitude decimal(11,8) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Provider Schedules
CREATE TABLE public.provider_schedules (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.users(id) on delete cascade,
  day_of_week int not null,
  start_time time not null,
  end_time time not null,
  break_start time,
  break_end time,
  slot_duration int default 30,
  is_enabled boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique (provider_id, day_of_week)
);

-- Task Catalog
CREATE TABLE public.task_catalog (
  id bigint generated by default as identity primary key,
  profession_id int not null references public.professions(id),
  name varchar(255) not null,
  pricing_type varchar(20) not null default 'fixed' check (pricing_type in ('fixed', 'per_unit')),
  unit_name varchar(64),
  unit_price decimal(10,2) not null,
  keywords varchar(1000),
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Service Categories (Legacy/Redundant but present in dump)
CREATE TABLE public.service_categories (
  id bigint generated by default as identity primary key,
  name varchar(50) not null unique,
  icon_slug varchar(50)
);

-- Service Requests
CREATE TABLE public.service_requests (
  id varchar(36) primary key, -- UUID
  client_id bigint not null references public.users(id),
  category_id int references public.service_categories(id),
  task_id int references public.task_catalog(id),
  profession varchar(128),
  provider_id bigint references public.users(id),
  description text,
  status varchar(50) not null default 'waiting_payment',
  latitude decimal(10,8),
  longitude decimal(11,8),
  address text,
  price_estimated decimal(10,2),
  price_upfront decimal(10,2),
  scheduled_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  location_type varchar(20) default 'client',
  arrived_at timestamp with time zone,
  payment_remaining_status varchar(20) default 'pending',
  contest_reason text,
  contest_status varchar(20) default 'none',
  contest_evidence jsonb,
  validation_code varchar(10),
  proof_photo varchar(255),
  proof_video varchar(255),
  proof_code varchar(255),
  status_updated_at timestamp with time zone default timezone('utc'::text, now()),
  completed_at timestamp with time zone
);

-- Service Tasks (Items within a request)
CREATE TABLE public.service_tasks (
  id bigint generated by default as identity primary key,
  service_id varchar(36) not null references public.service_requests(id) on delete cascade,
  name varchar(255) not null,
  quantity decimal(10,2) not null default 1.00,
  unit_price decimal(10,2) not null,
  subtotal decimal(10,2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Service Media
CREATE TABLE public.service_media (
  id bigint generated by default as identity primary key,
  service_id varchar(36) not null references public.service_requests(id) on delete cascade,
  media_key varchar(255) not null,
  media_type varchar(10) not null check (media_type in ('image', 'video', 'audio')),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Chat Messages (Unified)
CREATE TABLE public.chat_messages (
  id bigint generated by default as identity primary key,
  service_id varchar(36) not null references public.service_requests(id),
  sender_id bigint not null references public.users(id),
  content text,
  type varchar(20) default 'text',
  sent_at timestamp with time zone default timezone('utc'::text, now()),
  read_at timestamp with time zone
);

-- Reviews
CREATE TABLE public.reviews (
  id bigint generated by default as identity primary key,
  service_id varchar(36) not null references public.service_requests(id) on delete cascade,
  reviewer_id bigint not null references public.users(id) on delete cascade,
  reviewee_id bigint not null references public.users(id) on delete cascade,
  rating int not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(service_id, reviewer_id)
);

-- Transactions
CREATE TABLE public.transactions (
  id bigint generated by default as identity primary key,
  service_id varchar(36) not null references public.service_requests(id),
  user_id bigint not null references public.users(id),
  amount decimal(10,2) not null,
  type varchar(20) not null check (type in ('deposit', 'final_payment', 'payout', 'refund')),
  status varchar(20) default 'pending' check (status in ('pending', 'success', 'failed')),
  provider_ref varchar(255),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Notifications
CREATE TABLE public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title varchar(255) not null,
  body text,
  type varchar(50) not null,
  related_id varchar(255),
  read_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  data jsonb
);

-- User Devices (FCM Tokens)
CREATE TABLE public.user_devices (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token varchar(512) not null,
  platform varchar(20) not null default 'web',
  last_active timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, token)
);

-- System Settings
CREATE TABLE public.system_settings (
  key_name varchar(50) primary key,
  value jsonb,
  description text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable PostGIS if available (optional for now, using Haversine)
-- create extension if not exists postgis;
