-- Create missing AI search logs table (required by Edge Functions ai-classify / ai-feedback / ai-learn-from-logs)

CREATE TABLE IF NOT EXISTS public.ai_search_logs (
  id bigint generated by default as identity primary key,
  user_id uuid,
  user_query text not null,
  suggested_task_id bigint references public.task_catalog(id),
  selected_task_id bigint references public.task_catalog(id),
  similarity_score double precision,
  engine text,
  success boolean default false,
  integrated boolean default false,
  created_at timestamptz default now()
);

-- Basic indexes for dashboards/learning jobs
CREATE INDEX IF NOT EXISTS ai_search_logs_created_at_idx ON public.ai_search_logs (created_at desc);
CREATE INDEX IF NOT EXISTS ai_search_logs_success_integrated_idx ON public.ai_search_logs (success, integrated);

-- RLS enabled (service_role bypasses; clients need explicit policies if ever required)
ALTER TABLE public.ai_search_logs ENABLE ROW LEVEL SECURITY;

