-- Finance config for Uber-like flows
CREATE TABLE IF NOT EXISTS public.uber_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commission_rate NUMERIC(6,4) NOT NULL DEFAULT 0.1500,
  commission_cap_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  commission_cap_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure a default row exists
INSERT INTO public.uber_config (commission_rate, commission_cap_enabled, commission_cap_amount)
SELECT 0.1500, FALSE, 0
WHERE NOT EXISTS (SELECT 1 FROM public.uber_config);

-- Track total commission paid by driver
CREATE TABLE IF NOT EXISTS public.driver_commission_summary (
  user_id BIGINT PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  total_commission_paid NUMERIC(12,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add commission fields to payments
ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS commission_amount NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS commission_rate NUMERIC(6,4);

-- Update timestamp trigger for uber_config
DROP TRIGGER IF EXISTS update_uber_config_modtime ON public.uber_config;
CREATE TRIGGER update_uber_config_modtime
  BEFORE UPDATE ON public.uber_config
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- RLS
ALTER TABLE public.uber_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_commission_summary ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "UberConfig read" ON public.uber_config;
CREATE POLICY "UberConfig read"
ON public.uber_config
FOR SELECT
USING (auth.role() IN ('authenticated', 'service_role'));

DROP POLICY IF EXISTS "UberConfig write" ON public.uber_config;
CREATE POLICY "UberConfig write"
ON public.uber_config
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

DROP POLICY IF EXISTS "DriverCommission read own" ON public.driver_commission_summary;
CREATE POLICY "DriverCommission read own"
ON public.driver_commission_summary
FOR SELECT
USING (user_id IN (SELECT id FROM public.users WHERE supabase_uid = auth.uid()));

DROP POLICY IF EXISTS "DriverCommission write service" ON public.driver_commission_summary;
CREATE POLICY "DriverCommission write service"
ON public.driver_commission_summary
FOR ALL
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');
