-- Migration: Create vehicles table for Uber drivers
CREATE TABLE public.vehicles (
  id bigint generated by default as identity primary key,
  driver_id bigint not null references public.users(id) on delete cascade,
  model varchar(100) not null,
  color varchar(50),
  plate varchar(20) not null unique,
  year int,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable RLS
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public read vehicles" ON public.vehicles FOR SELECT USING (true);
CREATE POLICY "Drivers can manage own vehicle" ON public.vehicles FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.users 
    WHERE users.id = vehicles.driver_id 
    AND users.supabase_uid = auth.uid()
  )
);

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.vehicles;

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_vehicles_updated_at
    BEFORE UPDATE ON public.vehicles
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
