name = "meu-backend-node"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "conserta-db"
database_id = "f257cffb-ffc2-4ecc-92d2-2e571c7d626e"

[vars]
AI_BASE_URL = "https://ai-service.carrobomebarato.workers.dev/"

[triggers]
crons = ["* * * * *"]
