-- Table para rastrear status de validação biométrica dos motoristas
CREATE TABLE IF NOT EXISTS driver_biometric_validations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service_id UUID NOT NULL,
  rekognition_status TEXT NOT NULL DEFAULT 'pendente',
  rekognition_similarity NUMERIC(5,2),
  documents JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT driver_biometric_validations_service_user UNIQUE (user_id, service_id)
);

-- trigger para manter updated_at automático
CREATE OR REPLACE FUNCTION public.touch_driver_biometric_validations()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_touch_driver_biometric_validations
BEFORE UPDATE ON driver_biometric_validations
FOR EACH ROW EXECUTE FUNCTION public.touch_driver_biometric_validations();
