-- Migração Principal D1 (SQLite) para Supabase (PostgreSQL)

-- 1. Habilitando extensões (UUID e PostGIS se necessário para geolocalização futura, mas manteremos o padrão simples)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Limpando tabelas antigas (Cuidados na execução se já houve dados!)
DROP TABLE IF EXISTS provider_locations CASCADE;
DROP TABLE IF EXISTS app_config CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS notificacao_de_servicos CASCADE;
DROP TABLE IF EXISTS notification_registry CASCADE;
DROP TABLE IF EXISTS service_tasks CASCADE;
DROP TABLE IF EXISTS service_requests_new CASCADE;
DROP TABLE IF EXISTS task_catalog CASCADE;
DROP TABLE IF EXISTS provider_professions CASCADE;
DROP TABLE IF EXISTS professions CASCADE;
DROP TABLE IF EXISTS service_categories CASCADE;
DROP TABLE IF EXISTS wallet_transactions CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 3. Criando as novas tabelas readequadas para PostgreSQL
CREATE TABLE users (
    -- id INTEGER PRIMARY KEY AUTOINCREMENT foi substituído por autoincremento serial do Auth/Supabase ou BigInt
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid TEXT UNIQUE,
    supabase_uid UUID REFERENCES auth.users(id), -- A Lógica Nova que vincula a tabela public a Auth do Supabase!
    email TEXT UNIQUE,
    full_name TEXT,
    role TEXT CHECK (role IN ('client', 'provider', 'admin')),
    phone TEXT,
    avatar_url TEXT,
    fcm_token TEXT,
    password_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_seen_at TIMESTAMP WITH TIME ZONE,
    is_verified BOOLEAN DEFAULT FALSE
);

CREATE TABLE providers (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    commercial_name TEXT,
    address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    document_type TEXT,
    document_value TEXT,
    is_online BOOLEAN DEFAULT FALSE,
    rating_avg DOUBLE PRECISION DEFAULT 0.0,
    rating_count INTEGER DEFAULT 0,
    wallet_balance DOUBLE PRECISION DEFAULT 0.0,
    schedule_configs JSONB -- Nova coluna pra substituir configs engessadas de horários se preciso!
);

CREATE TABLE wallet_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id BIGINT REFERENCES users(id),
    service_id UUID,
    amount DOUBLE PRECISION,
    type TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE service_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name TEXT
);

CREATE TABLE professions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name TEXT, 
    category_id BIGINT REFERENCES service_categories(id)
);

CREATE TABLE provider_professions (
    provider_user_id BIGINT REFERENCES providers(user_id) ON DELETE CASCADE, 
    profession_id BIGINT REFERENCES professions(id) ON DELETE CASCADE,
    PRIMARY KEY(provider_user_id, profession_id)
);

CREATE TABLE task_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profession_id BIGINT REFERENCES professions(id),
    name TEXT,
    pricing_type TEXT,
    unit_name TEXT,
    unit_price DOUBLE PRECISION,
    keywords TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela Central de Agendamentos e Serviços
CREATE TABLE service_requests_new (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id BIGINT REFERENCES users(id),
    category_id BIGINT REFERENCES service_categories(id),
    task_id BIGINT REFERENCES task_catalog(id),
    profession_id BIGINT REFERENCES professions(id),
    description TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    address TEXT,
    price_estimated DOUBLE PRECISION,
    price_upfront DOUBLE PRECISION,
    provider_amount DOUBLE PRECISION,
    location_type TEXT,
    profession TEXT,
    provider_id BIGINT REFERENCES providers(user_id),
    status TEXT,
    scheduled_at TIMESTAMP WITH TIME ZONE,
    arrived_at TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    proof_video TEXT,
    completion_code TEXT,
    payment_remaining_status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE service_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id UUID REFERENCES service_requests_new(id) ON DELETE CASCADE,
    name TEXT,
    quantity DOUBLE PRECISION DEFAULT 1.0,
    unit_price DOUBLE PRECISION,
    subtotal DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela Usada pelas Notificações Firebase
CREATE TABLE notification_registry (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    fcm_token TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    is_online BOOLEAN DEFAULT FALSE,
    professions_ids JSONB,
    last_seen_at TIMESTAMP WITH TIME ZONE,
    radius_km DOUBLE PRECISION DEFAULT 50.0
);

-- Fila de Notificações Ativa
CREATE TABLE notificacao_de_servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id UUID REFERENCES service_requests_new(id) ON DELETE CASCADE,
    provider_user_id BIGINT REFERENCES providers(user_id),
    fcm_token TEXT,
    status TEXT,
    last_notified_at TIMESTAMP WITH TIME ZONE,
    service_name TEXT,
    profession_id BIGINT,
    price_total DOUBLE PRECISION,
    price_provider DOUBLE PRECISION,
    commission_rate DOUBLE PRECISION,
    distance DOUBLE PRECISION,
    service_latitude DOUBLE PRECISION,
    service_longitude DOUBLE PRECISION,
    provider_latitude DOUBLE PRECISION,
    provider_longitude DOUBLE PRECISION,
    notification_count INTEGER DEFAULT 0,
    queue_order INTEGER,
    ciclo_atual INTEGER DEFAULT 1
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id UUID REFERENCES service_requests_new(id),
    user_id BIGINT REFERENCES users(id),
    amount DOUBLE PRECISION,
    status TEXT,
    mp_payment_id TEXT,
    payment_method_id TEXT,
    payer_email TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE app_config (
    key TEXT PRIMARY KEY,
    value TEXT,
    type TEXT
);

CREATE TABLE provider_locations (
    provider_id BIGINT PRIMARY KEY REFERENCES providers(user_id),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Função Automática para Triggers de Updated_At
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_service_requests_modtime
    BEFORE UPDATE ON service_requests_new
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Seed Data Inicial
INSERT INTO app_config (key, value, type) VALUES ('platform_commission_rate', '15', 'number');
INSERT INTO service_categories (name) VALUES ('Assistencia Tecnica'), ('Eletricista');
INSERT INTO professions (name, category_id) VALUES ('Chaveiro', 1), ('Eletricista', 2);
INSERT INTO task_catalog (profession_id, name, unit_price) VALUES (2, 'Troca de fiação', 100.0);
