-- Tabelas Faltantes para Migração Completa

-- 1. Agendamentos (Appointments)
CREATE TABLE IF NOT EXISTS appointments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    service_request_id UUID REFERENCES service_requests_new(id) ON DELETE CASCADE,
    provider_id BIGINT REFERENCES providers(user_id),
    client_id BIGINT REFERENCES users(id),
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'waiting_payment')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Notificações In-App (para Central de Notificações)
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    title TEXT,
    body TEXT,
    data JSONB,
    read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Logs de Eventos de Serviço (Auditoria Dispatcher)
CREATE TABLE IF NOT EXISTS service_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id UUID REFERENCES service_requests_new(id) ON DELETE CASCADE,
    provider_id BIGINT REFERENCES providers(user_id),
    action TEXT,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Exceções de Agenda do Prestador
CREATE TABLE IF NOT EXISTS provider_schedule_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT REFERENCES providers(user_id) ON DELETE CASCADE,
    date DATE NOT NULL,
    is_available BOOLEAN DEFAULT FALSE,
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS em tudo
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE provider_schedule_exceptions ENABLE ROW LEVEL SECURITY;

-- Políticas Simples (Ajustar conforme necessário)
DROP POLICY IF EXISTS "Users can see their own appointments" ON appointments;
CREATE POLICY "Users can see their own appointments" ON appointments FOR SELECT USING (auth.uid() IN (SELECT supabase_uid FROM users WHERE id = client_id OR id = provider_id));

DROP POLICY IF EXISTS "Users can see their own notifications" ON notifications;
CREATE POLICY "Users can see their own notifications" ON notifications FOR SELECT USING (auth.uid() IN (SELECT supabase_uid FROM users WHERE id = user_id));

DROP POLICY IF EXISTS "Users can update their own notifications" ON notifications;
CREATE POLICY "Users can update their own notifications" ON notifications FOR UPDATE USING (auth.uid() IN (SELECT supabase_uid FROM users WHERE id = user_id));

-- Realtime para Notificações e Agendamentos  
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE appointments;
EXCEPTION WHEN OTHERS THEN NULL; -- Ignora se já estiver na publicação
END $$;

DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;
