-- Migração para adicionar suporte a Avaliações e Geolocalização

-- 1. Tabela de Avaliações
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id UUID REFERENCES service_requests_new(id) ON DELETE CASCADE,
    reviewer_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    reviewee_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(service_id, reviewer_id)
);

-- 2. Trigger para atualizar a média de avaliação do prestador automaticamente
CREATE OR REPLACE FUNCTION update_provider_rating()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE providers
    SET 
        rating_avg = (SELECT AVG(rating) FROM reviews WHERE reviewee_id = NEW.reviewee_id),
        rating_count = (SELECT COUNT(*) FROM reviews WHERE reviewee_id = NEW.reviewee_id)
    WHERE user_id = NEW.reviewee_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_provider_rating
AFTER INSERT OR UPDATE ON reviews
FOR EACH ROW EXECUTE FUNCTION update_provider_rating();

-- 3. Tabela de Cache de Geolocalização (Opcional, para reduzir custos de API)
CREATE TABLE IF NOT EXISTS geo_cache (
    query TEXT PRIMARY KEY,
    response JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Habilitar RLS nas novas tabelas
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE geo_cache ENABLE ROW LEVEL SECURITY;

-- Políticas Simples: Qualquer usuário logado pode ler reviews, mas apenas o reviewer pode criar/editar a sua.
CREATE POLICY "Reviews são públicas" ON reviews FOR SELECT USING (true);
CREATE POLICY "Usuários podem criar suas próprias reviews" ON reviews FOR INSERT WITH CHECK (
    auth.uid() IN (SELECT supabase_uid FROM users WHERE id = reviewer_id)
);
