-- Tabela para Histórico de Localização em Tempo Real (Tracking)
CREATE TABLE IF NOT EXISTS service_location_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id UUID REFERENCES service_requests_new(id) ON DELETE CASCADE,
    provider_id BIGINT REFERENCES providers(user_id),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    accuracy DOUBLE PRECISION,
    speed DOUBLE PRECISION,
    timestamp BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar Realtime para esta tabela (Crucial para o Gossip Mode)
ALTER PUBLICATION supabase_realtime ADD TABLE service_location_history;

-- RLS
ALTER TABLE service_location_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Qualquer um pode ler o histórico de localização" ON service_location_history FOR SELECT USING (true);
CREATE POLICY "Prestadores podem inserir seu próprio histórico" ON service_location_history FOR INSERT WITH CHECK (
    auth.uid() IN (SELECT supabase_uid FROM users WHERE id = provider_id)
);
